In [10]:
import numpy as np

L = np.array([[1,2,3,4,5],[6,7,8,9,10]])
L

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
L[1,2]

8

In [13]:
C = np.array([1,2,3,4,5], int)
print(C)
D = np.array([1,2,3,4,5], dtype=float)
print(D)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [44]:
E = np.arange(9)
print(E)

F = np.arange(1,6,2)
print(F)

b = E[3:]
print(b)
c = E[::-1]
print(c)
d = E[::2]
print(d)
F = E[2:9:3]
print(F)

[0 1 2 3 4 5 6 7 8]
[1 3 5]
[3 4 5 6 7 8]
[8 7 6 5 4 3 2 1 0]
[0 2 4 6 8]
[2 5 8]


In [17]:
np.zeros((2,2), int)

array([[0, 0],
       [0, 0]])

In [20]:
a = np.arange(16)
b = a.reshape((4,4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
L = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for ele in L:
    print(ele, end=' ')
print()
for ele1 in L:
    for ele2 in ele1:
        print(ele2, end=' ')

[1 2 3 4 5] [ 6  7  8  9 10] 
1 2 3 4 5 6 7 8 9 10 

In [31]:
import numpy as np
a = np.random.randn(5,4)
a

array([[ 2.28699304, -0.07993159, -0.39263831,  0.54767839],
       [-1.80748717, -1.21288439, -0.4817636 , -0.25127074],
       [ 0.36805714, -1.10003101, -0.42927994,  0.06523331],
       [ 0.27474172,  1.4163847 ,  0.5009089 , -0.40136549],
       [-1.07005801,  1.12701103, -1.49642626,  0.26375702]])

In [34]:
import numpy as np
a = np.array([1,3])
b = np.array([5,8])
norm_park = np.linalg.norm(a-b)
norm_park

6.4031242374328485

In [51]:
import numpy as np
b = np.array([1,2,3,4,5,6])
mask = (b % 2 ==0)
print(mask)

mask1 = np.array([1,0,1,1,0], dtype = bool)
print(mask1)

[False  True False  True False  True]
[ True False  True  True False]


In [53]:
L = np.array([[1,2,3,4,5],[6,7,8,9,10]])
b = L.ravel()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
import numpy as np
a = np.array([[1,3,6],[1,3,6]])
b = np.array([[5,8,5],[8,9,10]])

c = np.concatenate((a,b), axis = 1)
c

array([[ 1,  3,  6,  5,  8,  5],
       [ 1,  3,  6,  8,  9, 10]])

In [64]:
x = np.arange(0, 10).reshape(2,5)
print(x)
weight = [0.3, 0.7]
np.average(x, axis=0, weights=weight)

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([3.5, 4.5, 5.5, 6.5, 7.5])

In [68]:
y = np.array([4,5,1,8,47,6,1,85])

np.piecewise(y, [y<4, y>10], [lambda y:y*2, lambda y:y/10])

array([0, 0, 2, 0, 4, 0, 2, 8])